Find uno.lib (debug)

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -286,6 +286,11 @@ jobs:
       # BUILD
       # =========================================================
 
+      - name: Find uno.lib (debug)
+        if: matrix.toolchain == 'msvc' && matrix.library == 'shared'
+        shell: cmd
+        run: dir /s /b build\uno.lib 2>nul || echo "uno.lib not found"
+
       - name: Build
         run: cmake --build build --target run_unotest --config ${{env.BUILD_TYPE}}
 
